In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("survey_results_public.csv")
df1 = pd.read_csv("survey_results_schema.csv")

C:\Users\Яніна\AppData\Local\Temp\ipykernel_23528\1593025224.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("survey_results_public.csv")

In [3]:
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [4]:
df1.head()

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

In [5]:
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df1

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [7]:
#завдання 1
total_respondents = df["ResponseId"].nunique()

print(total_respondents)

49191

In [8]:
#завдання 2
questions = set(df1["qname"].unique())
questions = questions.intersection(df.columns)
complete_responses = df[list(questions)].dropna().shape[0]

print(complete_responses)

0

In [9]:
#завдання 3
print('Міри центральної тенденції:')
# Середнє
print(f'Mean: {round(df["WorkExp"].mean(), 1)}')
# Медіана
print(f'Median: {df["WorkExp"].median()}')
# Мода
print(f'Mode: {df["WorkExp"].mode()[0]}')

Міри центральної тенденції:
Mean: 13.4
Median: 10.0
Mode: 10.0

In [10]:
#завдання 4
remote_workers = df[df["RemoteWork"] == "Remote"].shape[0]

print(remote_workers)

10931

In [11]:
#завдання 5
worked_with_python = df["LanguageHaveWorkedWith"].str.contains(
    "Python",
    case=False,
    na=False
)

python_percentage = (worked_with_python.sum() / len(df)) * 100

print(f"Відсоток респондентів: {round(python_percentage, 1)}%")

Відсоток респондентів: 37.5%

In [12]:
#завдання 6
learned_with_online_courses = df["LearnCode"].str.contains(
    "Online Courses",
    case=False,
    na=False
)

online_courses_count = learned_with_online_courses.sum()

print(online_courses_count)

10973

In [13]:
#завдання 7
worked_with_python = df[
    df["LanguageHaveWorkedWith"].str.contains(
        "Python",
        case=False,
        na=False
    )
]
worked_with_python = worked_with_python.dropna(
    subset=["ConvertedCompYearly"]
)
py_progerrs_by_country = worked_with_python.groupby("Country")[
    "ConvertedCompYearly"
].agg(["mean", "median"])

print(py_progerrs_by_country)

                                               mean    median
Country
Afghanistan                            22328.666667    1000.0
Albania                                47217.600000   50000.0
Algeria                                20187.285714    7088.0
Andorra                               226103.500000  226103.5
Antigua and Barbuda                        1.000000       1.0
...                                             ...       ...
Venezuela, Bolivarian Republic of...    9908.647059    3000.0
Viet Nam                              218837.166667    8254.0
Yemen                                  32929.500000   23672.0
Zambia                                  5424.250000    3206.0
Zimbabwe                               34000.000000   25500.0

[153 rows x 2 columns]

In [14]:
#завдання 8
top_paid = df[
    ["ResponseId", "EdLevel", "ConvertedCompYearly"]
    ]
top_paid = top_paid.dropna(subset=["ConvertedCompYearly"])
top_paid = top_paid.sort_values(
    by="ConvertedCompYearly",
    ascending=False
)
top_5 = top_paid.head(5).reset_index(drop=True)
print(top_5)

   ResponseId                                          EdLevel  \
0       34268              Associate degree (A.A., A.S., etc.)
1       28701  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
2       43144              Associate degree (A.A., A.S., etc.)
3       35354     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4       45972  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

   ConvertedCompYearly
0           50000000.0
1           33552715.0
2           18387548.0
3           15430267.0
4           13921760.0

In [15]:
#завдання 9
df["UsesPython"] = df["LanguageHaveWorkedWith"].str.contains(
    "Python",
    case=False,
    na=False
)

python_by_age = df.groupby("Age").agg(
    total_respondents=("ResponseId", "count"),
    python_users=("UsesPython", "sum")
)

python_by_age["python_percentage"] = (
    python_by_age["python_users"]
    / python_by_age["total_respondents"]
) * 100

python_by_age["python_percentage"] = (
    python_by_age["python_percentage"].round(1)
)

print(python_by_age[["python_percentage"]])

                   python_percentage
Age
18-24 years old                 40.0
25-34 years old                 36.9
35-44 years old                 36.7
45-54 years old                 38.6
55-64 years old                 37.2
65 years or older               31.6
Prefer not to say               31.2

In [16]:
#завдання 9
salary_75 = df["ConvertedCompYearly"].quantile(0.75)
high_paid_remote = df[
    (df["ConvertedCompYearly"] > salary_75)
    &
    (df["RemoteWork"] == "Remote")
]
top_industries = high_paid_remote["Industry"].value_counts()

print(top_industries)

Industry
Software Development                          1186
Fintech                                        190
Healthcare                                     188
Other:                                         176
Internet, Telecomm or Information Services     138
Banking/Financial Services                      88
Government                                      78
Media & Advertising Services                    75
Retail and Consumer Services                    65
Transportation, or Supply Chain                 63
Computer Systems Design and Services            59
Insurance                                       46
Energy                                          45
Manufacturing                                   33
Higher Education                                30
Name: count, dtype: int64